[book]
authors = ["josh rotenberg"]
language = "en"
multilingual = false
src = "src"
title = "josh rotenberg"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/joshrotenberg/joshrotenberg.github.io/tree/main"
edit-url-template = "https://github.com/joshrotenberg/joshrotenberg.github.io/edit/main/{path}"
default-theme = "coal"

[output.html.fold]
enable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2